trigger:
  - master

pr:
  - master

pool:
  vmImage: windows-latest

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  versionMajor: 2.0
  versionMinor: $[counter(variables['versionMajor'], 100)]

name: $(versionMajor).$(versionMinor)

stages:
  - stage: Build
    jobs:
      - job: build
        pool:
          vmImage: windows-2022
        variables:
          solution: '**\*.sln'
          buildPlatform: Any CPU
          buildConfiguration: Release
        steps:
          - task: NuGetToolInstaller@1
            displayName: install nuget
            inputs:
              versionSpec: 6.3.1

          - pwsh: build\update-version.ps1 -Version $(Build.BuildNumber)
            displayName: "update version"

          - task: NuGetCommand@2
            displayName: nuget restore
            inputs:
              command: restore

          - task: VSBuild@1
            displayName: build solution
            inputs:
              solution: $(solution)
              platform: $(buildPlatform)
              configuration: $(buildConfiguration)
              maximumCpuCount: true

          - task: CopyFiles@2
            displayName: prepare artifact
            inputs:
              SourceFolder: "$(Build.SourcesDirectory)"
              Contents: |
                README.md
                build/**
                **/*.vsix
              TargetFolder: $(Build.ArtifactStagingDirectory)

          - publish: $(Build.ArtifactStagingDirectory)
            displayName: publish artifact
            artifact: package

  - stage: deploy
    dependsOn:
      - build
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    jobs:
      - deployment: publish_vsix
        displayName: publish vsix package
        pool:
          vmImage: windows-2022
        environment: production
        strategy:
          runOnce:
            deploy:
              steps:
                - pwsh: $(Pipeline.Workspace)/package/build/publish-vsix.ps1 -PersonalAccessToken $(MarketplacePAT)
                  displayName: publish vsix to marketplace
